apiVersion: v2
name: rancher-k8s-auditlog-collector
type: application
description: collect k8s auditlog for rancher auditlog server
version: 0.0.1
appVersion: "1.8.13"
kubeVersion: ">= 1.18.0-0"
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png